### ISSUE TITLE
Die Readme bringt Leute dazu, ggf. unnötig eine zweite Sprache anzulegen

### ISSUE THREAD

**Issue by spackmat** [jmartsch/pw-lang-de#50]
Die Readme beschreibt aktuell die Installation so, dass eine zweite Sprache anzulegen ist, um das Sprachpaket nutzen zu können. Das ist irreführend, weil bei einfachen einsprachigen Installationen, die ein deutsches Backend haben sollen, auf diese Weise eine unnötig komplizierte Mehrsprachigkeit entsteht (und die Loginseite ist dann noch immer englisch).

Ich schlage vor, bei der Installationsbeschreibung einen Einschub einzufügen, der beschreibt, wie man eine neue Sprache anlegt. Und ansonsten wird beschrieben, dass man das Sprachpaket in der gewünschten Websitesprache hochlädt (default für eine primär deutsche Seite oder die angelegte deutsche Sprache für mehrsprachige Seiten).

Liebe Grüße
Gregor

**Comment by jmartsch** [comment]
Hey @spackmat Ich habe in einem großen Projekt den Fehler gemacht, die Default Sprache zu ändern und Deutsch als default zu benutzen. Dies hat hat diverse Probleme aufgeworfen, welche ich im Detail nicht mehr weiß. Das bessere Prozedere ist es, eine neue Sprache anzulegen und dann den User "guest" auf diese Sprache zu stellen.
Und natürlich auch für alle anderen User für die der Adminbereich oder die Website auf Deutsch erscheinen soll.

**Comment by spackmat** [comment]
Wenn man eine zweite Sprache anlegt, holt man sich halt allerlei Komplexität ins Haus, etwa dass alle Felder und Templates zwei Beschriftungen haben wollen. Kann man weglassen und die deutsche Beschriftung ins Defaultfeld schreiben, aber das ist ja eigentlich englisch. Also endet man damit, dass man doch zwei Beschriftungen vergibt. Und man muss bei allen Feldern, die Zweisprachigkeit unterstützen, die wieder wegkonfigurieren (wenn das überhaupt geht), weil die Redakteur_innen sonst zwei Eingabefelder sehen und gar nicht verstehen wieso. Ich hatte damit zudem immer mal wieder Ärger, etwa mit einem echt nervigen Bug im image_extra Modul, wo letztlich weder die eine noch die andere Sprache gespeichert wurde. Solche Sachen sind doof genug, wenn das Projekt mehrsprachig ist, aber völlig unnötig bei einsprachigen Projekten. Bei Websites, die sicher nicht zweisprachig sein werden, spart man sich den ganzen Spaß im Hintergrund mit all seinen möglichen Seiteneffekten, wenn man das Sprachpaket einfach der Defaultsprache hinzufügt. Man kann ja darauf hinweisen, dass es eine gute Idee sein kann, Deutsch als Zweitsprache zu konfigurieren. Aber aktuell liest sich die Anleitung halt so, als müsste man das so machen. Mich hat das in eine nervige Falle gelockt, als ich neu im Thema war und es hat einige Mühe gemacht, das wieder geradezubiegen.

**Comment by jmartsch** [comment]
@spackmat Danke für dein Feedback, ich werde das noch mal überprüfen und schauen, ob der von dir vorgeschlagene Weg praktikabel und ohne Fehler ist.

**Comment by jmartsch** [comment]
Hey @spackmat ich stimme mit deiner Aussage überein und habe auch das Readme angepasst und auf ein gutes Tutorial im Forum verwiesen, mit welchem man die Default-Sprache ändern kann.
